### ISSUE TITLE
matched no packages

### ISSUE THREAD

**Issue by cclulu** [oakmound/oak#104]
Hey, so I wanted to try out this package, but when I try
    `go get -u github.com/oakmound/oak/v2...` 
I get 
    `go: warning: "github.com/oakmound/oak/v2..." matched no packages` 
I tried changing it to 
`go get -u github.com/oakmound/oak/v2/...` 

i get the same thing. Here is my go setup:
``` bash
export GOPATH="$HOME/go"
export GO="/usr/local/Cellar/go/1.13.8"
export GOROOT="$GO/libexec"
export PATH=$GO/bin:$GOPATH/bin:$PATH
```
is there something obvious I am missing?

Thanks for the help!

by the way, `go get -u github.com/oakmound/oak/...` works i  believe, but just a couple of deprecation warnings.

**Comment by 200sc** [comment]
Are you calling this from with a go module?

**Comment by 200sc** [comment]
The missing slash in the readme is a typo, too, thank you for catching that.

**Comment by cclulu** [comment]
No I did not try within a go module, sorry I am new to go modules. I first had to make my location a go module, then it could find it right away. I knew it was probably something simple that i was missing, thanks for the help. I will close this issue.

**Comment by 200sc** [comment]
No worries, the modules story is confusing. It's a little unfortunate because oak released a v2 before they were introduced, so our solution for them is kind of awkwardly backported. 

If you just want to mess around with the examples, running the `go get` without the `v2` outside of a module lets you cd into the directory in the gopath and run the examples.

 The syntax with the `v2` import would be if you build a package with oak as a dependency.
