### ISSUE TITLE
LayeredPoint should not have GetDims(), and it **really** shouldn't always return 6,6

### ISSUE THREAD

**Issue by lolbinarycat** [oakmound/oak#117]
I was wondering why GetDims() on render.CompositeR didn't seem to be working. so I looked for the method definition. Nothing. well, it embeds DrawPolygon, maybe It's on that. Nope. After some searching in the code, I find it, and see this:
```go
return 6,6
```
1. It's a point, it dosn't have dimentions
2.  ***WHAT***

**Comment by 200sc** [comment]
This is to correct a bug as referred to by #72. The history of this is that polyclip go innacurately reported containment for sizes smaller than 6. Will provide more details later.

**Comment by 200sc** [comment]
Posting the comment in the code that explains these values for posterity:
```
// We use 6,6 here because our polygon containment library has a bug where it
	// will misreport artificially small dimensions. This function is expected to
	// only be used to determine whether something is onscreen to be drawn.
	// Todo: write own polygon containment library```

**Comment by lolbinarycat** [comment]
Yes, but the method that that comment is in is embedded in a type that was stored as an interface type. It dosn't really help if there's a comment explaining it 3 levels down.

**Comment by lolbinarycat** [comment]
and DrawPolyganDim (the best alternative I could find) also doesn't work. Also, just one dimension?

**Comment by lolbinarycat** [comment]
also, why is `usingDrawPolygonDim` a field? that dosn't sound good.

**Comment by 200sc** [comment]
The reason Composite does not have a GetDims is because what exactly that means is not clear and not easy to calculate-- do you want the dimensions of a single piece of the composite, or do you want to pseudo draw all of the elements and determine how big of a box those things would fill? If one of the items changes position, should that change the result of the function? This type and several others do not implement GetDims because it is infeasible to do so, and just use the default from LayeredPoint. 

This is also exactly why LayeredPoint has GetDims in the first place, to make it easier to create a Renderable type without needing to specify this strange (6,6) w/h to get your dimensions respected by the bug in the draw heap. That bug is since fixed, so we can undo this in 3.0, as is the plan set out by the issue that fixed the bug.

As for DrawPolygon, please refer to the documentation of the type: 
```
// A DrawPolygon is used to determine whether elements should be drawn, defining
// a polygonal area for what things should be visible.
```
It has nothing to do with the dimensions of a specific renderable or drawn element. Its purpose is to restrict what is drawn to the screen. The boolean flag `usingDrawPolygon` sets whether it is in use or not, as it is embedded into Stackable types. That is why it is imported by CompositeR-- CompositeR is a Stackable type that may want to restrict what should be drawn to the screen based on a polygon overlay on the screen.

**Comment by 200sc** [comment]
As for "just one dimension", `DrawPolygonDim` returns a rectangle.

**Comment by lolbinarycat** [comment]
So it should've been called DrawPolygonBounds.
Well I've already gone and implemented a naive method for GetDims that assumes that all the elements overlap, which will work in my case.

**Comment by Implausiblyfun** [comment]
Naming is hard aliasing is easy :)

**Comment by 200sc** [comment]
The function has been aliased and deprecated. Is there anything else you would like to raise in this issue @lolbinarycat , or may it be closed?

**Comment by lolbinarycat** [comment]
I guess it can be closed.
