### ISSUE TITLE
Revamp Particles Recycling

### ISSUE THREAD

**Issue by Implausiblyfun** [oakmound/oak#6]
Particle Sources should have their recycle mechanics overhauled. This should make particles more efficient.
Since particles are performance intensive how the recycling of particles works needs to be carefully considered otherwise it can end up making performance much worse rather than better.

**Comment by 200sc** [comment]
To be more specific: right now particle `Source`s have a `recycled []int` field which just keeps track of what indices in their block of particles have already been made but could be reused. 

The idea is to, instead of using this, swap dead particles in the block with the final live particle, so we just need to keep track of the current number of active particles.

**Comment by 200sc** [comment]
To do this, we'll need a function to set a particle's `pid` field, because collision particles need their space updated to have their new id. That's a breaking change to the particle interface, so this is 2.0.

**Comment by 200sc** [comment]
This is complete on release/2.0.0.
