### ISSUE TITLE
Closing the game window doesn't end the running process [OSX]

### ISSUE THREAD

**Issue by martskins** [oakmound/oak#78]
Closing a running app's window doesn't end the process, the terminal still shows the following:

```
➜  client go run main.go
[config:189]  [{{assets/ audio/ images/ font/} { ERROR} {0 0 480 640 1} {none 12 72  white} 60 60 English Oak Window false false false}]

~~~~~~~~~~~~~~~
Oak Seed: 1518833204632604000

~~~~~~~~~~~~~~~
```

To actually end the process a Ctrl + C is needed.

OS: mac OS High Sierra 10.13.1
`go version go1.9.2 darwin/amd64`

This happens both on the master and develop branch

**Comment by 200sc** [comment]
I imagine this is because the gldriver in shiny isn't sending events when it exits, but I'll have to look into it, probably this weekend.

**Comment by 200sc** [comment]
So, yes, this is apparently a year-and-a-half old bug in shiny noted by this todo:

https://github.com/oakmound/shiny/blob/dc1f35f043173830d2404693dc02825d3e69c754/driver/gldriver/cocoa.m#L210-L214

One potential fix is to just always call `windowClosing`, then check for nil and release if necessary. In the best case scenario that would just occasionally end up with multiple "Dead" events getting sent, which shouldn't matter because oak exits after receiving a single one.

**Comment by 200sc** [comment]
As far as fixing this any time soon goes (which I'd like to!), I might be able to get my hands on a mac to test it within the next week but if anyone who already has one would dig into this that would be helpful
